# Generated by Django 5.1.4 on 2024-12-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookStore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=30, unique=True),
        ),
    ]
