# Generated by Django 5.1.4 on 2024-12-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookStore", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
