# Generated by Django 5.1.4 on 2024-12-11 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookStore", "0003_alter_user_is_active_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="end_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
